POST http://localhost:8080/applications
Content-Type: application/json

{
  "company": "Google",
  "position": "Web Developer",
  "status": "OFFER",
  "location": "Cape Town",
  "notes": "Applied through LinkedIn"
}