POST http://localhost:8080/applications
Content-Type: application/json

{
  "company": "Microsoft",
  "position": "Junior Software Developer",
  "status": "INTERVIEW",
  "location": "Pretoria",
  "notes": "Applied through LinkedIn"
}